export const categories = [
  { name: "Choose a category", id: 0 },
  { name: "Motorcycles", id: 1 },
  { name: "Motorcycles Parts", id: 2 },
  { name: "Cars", id: 3 },
  { name: "Car Parts", id: 4 },
  { name: "Boats", id: 5 },
  { name: "Boat Parts", id: 6 },
  { name: "Foods", id: 7 },
  { name: "Comics", id: 8 },
  { name: "Novels", id: 9 },
  { name: "Electronics", id: 10 },
  { name: "Hunting", id: 11 },
  { name: "Fishing", id: 12 },
  { name: "Tools", id: 13 },
  { name: "Animals", id: 14 },
  { name: "Shoes", id: 15 },
  { name: "Phones", id: 16 },
  { name: "Furniture", id: 17 },
  { name: "Music", id: 18 },
  { name: "He-Man figures", id: 19 },
  { name: "Concert tickets", id: 20 },
];
