
const mockUsers = [
  {
    "id": "1",
    "firstName": "Timmy",
    "lastName": "Thomson",
    "email": "timmythomson@gmail.com",
    "password": "tomat",
    "phone": "700555444",
    "street": "Tistelvägen 5",
    "city": "Tranemo",
    "postalCode": 55500,
    "country": "Sweden",
    "latitude": 57.485569,
    "longitude": 13.35241,
  },
  {
    "id": "2",
    "firstName": "Jonna",
    "lastName": "Johansson",
    "email": "Jonna@gmail.com",
    "password": "jeans",
    "phone": "700123456",
    "street": "järnvägen 1",
    "city": "Jakobsberg",
    "postalCode": 12300,
    "country": "Sweden",
    "latitude": 59.422571,
    "longitude": 17.833131,
  },
  {
    "id": "3",
    "firstName": "Donny",
    "lastName": "Disaster",
    "email": "DisasterD@outlook.com",
    "password": "dragkrok",
    "phone": "700666666",
    "street": "Downtown 1",
    "city": "Edinburgh",
    "postalCode": 12345,
    "country": "UK",
    "latitude": 55.94918,
    "longitude": -3.209806,
  },
  {
    "id": "4",
    "firstName": "Jocke",
    "lastName": "Jansson",
    "email": "BigJ@yahoo.com",
    "password": "jacka",
    "phone": "705111222",
    "street": "Jurkyrkogården",
    "city": "Jockmock",
    "postalCode": 32165,
    "country": "Sweden",
    "latitude": 66.606961,
    "longitude": 19.822921,
  },
  {
    "id": "5",
    "firstName": "Kicki",
    "lastName": "Karatespark",
    "email": "HiYaaa@icloud.com",
    "password": "kickbike",
    "phone": "709876543",
    "street": "Kickass street 1",
    "city": "Karlstad",
    "postalCode": 45678,
    "country": "Sweden",
    "latitude": 59.402181,
    "longitude": 13.511498,
  }
]

export default mockUsers;
